// Code generated by Kitex v0.7.0. DO NOT EDIT.

package followingservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	relation "github.com/houqingying/douyin-lite/kitex/kitex_gen/relation"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	FollowingAction(ctx context.Context, Req *relation.FollowingActionRequest, callOptions ...callopt.Option) (r *relation.FollowingActionResponse, err error)
	FollowingList(ctx context.Context, Req *relation.FollowingListRequest, callOptions ...callopt.Option) (r *relation.FollowingListResponse, err error)
	FollowerList(ctx context.Context, Req *relation.FollowerListRequest, callOptions ...callopt.Option) (r *relation.FollowerListResponse, err error)
	FriendList(ctx context.Context, Req *relation.FriendListRequest, callOptions ...callopt.Option) (r *relation.FriendListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kFollowingServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFollowingServiceClient struct {
	*kClient
}

func (p *kFollowingServiceClient) FollowingAction(ctx context.Context, Req *relation.FollowingActionRequest, callOptions ...callopt.Option) (r *relation.FollowingActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowingAction(ctx, Req)
}

func (p *kFollowingServiceClient) FollowingList(ctx context.Context, Req *relation.FollowingListRequest, callOptions ...callopt.Option) (r *relation.FollowingListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowingList(ctx, Req)
}

func (p *kFollowingServiceClient) FollowerList(ctx context.Context, Req *relation.FollowerListRequest, callOptions ...callopt.Option) (r *relation.FollowerListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowerList(ctx, Req)
}

func (p *kFollowingServiceClient) FriendList(ctx context.Context, Req *relation.FriendListRequest, callOptions ...callopt.Option) (r *relation.FriendListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FriendList(ctx, Req)
}
